spring.application.name=sandbox_backend
spring.threads.virtual.enabled=true

#ENV_Variables
JWT_SECRET=YOUR_SECRET

# DataSource Configuration for PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:postgres}
spring.datasource.username=postgres
spring.datasource.password=password

# JPA / Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=PORT

# Logging
logging.level.org.springframework.security=DEBUG